#Archetypes
!setname 0xf86 Limit Break
!setname 0xb67 World Decoder
!setname 0x7f6 Umbra Witch
!setname 0x704 Infernal Demon
!setname 0x8f6 Creation God
!setname 0xcb0 Lumen Sage
!setname 0xb20 Demon Masquerade
!setname 0xd8f Nocturne Gear
!setname 0xa58 Endless
!setname 0xb18 World Breaker
!setname 0xc25 Detonator
!setname 0x989 Pyrea
!setname 0x8ec Lawrence